#!/bin/sh

grabbers=""
foundfiles=""

get_grabbers()
{
IFS=:
for p in $PATH; do
  files=$(find $p -type f -name "tv_grab*")
  if [ ! -z $files ]; then
    foundfiles="$foundfiles$files"
  fi
done
}

check_grabber()
{
IFS="
"
i=0
for f in $foundfiles
do
#  echo $f             
  if [ -x "$f" ]
  then                   
    f_out=$($f --description 2>/dev/null)
    if [ ! -z "$f_out" ]
    then
      tmp="$f|$f_out"
#      echo $tmp   
      grabbers="$grabbers:$tmp"
      i=$((i+1))
    fi
  fi
done
}

print_grabbers()
{
IFS=:             
for g in $grabbers
do       
  if [ ! -z "$g" ]
  then
    echo "$g"
  fi
done
}

get_grabbers 
check_grabber 
print_grabbers
